ALTER TYPE "DialogStateType" ADD VALUE IF NOT EXISTS 'CATEGORY_RENAME_WAITING_FOR_TYPE';
ALTER TYPE "DialogStateType" ADD VALUE IF NOT EXISTS 'CATEGORY_RENAME_WAITING_FOR_OLD_NAME';
ALTER TYPE "DialogStateType" ADD VALUE IF NOT EXISTS 'CATEGORY_RENAME_WAITING_FOR_NEW_NAME';
